/* automatically generated by rust-bindgen 0.57.0 */

pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type size_t = ::std::os::raw::c_ulong;
pub type va_list = __builtin_va_list;
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _flags2: ::std::os::raw::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub __pad5: size_t,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
pub type ulong = ::std::os::raw::c_ulong;
pub type uint = ::std::os::raw::c_uint;
pub type byte = ::std::os::raw::c_uchar;
pub type tmbchar = ::std::os::raw::c_char;
pub type tmbstr = *mut tmbchar;
pub type ctmbstr = *const tmbchar;
pub const Bool_no: Bool = 0;
pub const Bool_yes: Bool = 1;
pub type Bool = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyIterator {
    pub _opaque: ::std::os::raw::c_int,
}
pub type TidyIterator = *const _TidyIterator;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyOptionId {
    TidyUnknownOption = 0,
    TidyAccessibilityCheckLevel = 1,
    TidyAltText = 2,
    TidyAnchorAsName = 3,
    TidyAsciiChars = 4,
    TidyBlockTags = 5,
    TidyBodyOnly = 6,
    TidyBreakBeforeBR = 7,
    TidyCharEncoding = 8,
    TidyCoerceEndTags = 9,
    TidyCSSPrefix = 10,
    TidyCustomTags = 11,
    TidyDecorateInferredUL = 12,
    TidyDoctype = 13,
    TidyDoctypeMode = 14,
    TidyDropEmptyElems = 15,
    TidyDropEmptyParas = 16,
    TidyDropPropAttrs = 17,
    TidyDuplicateAttrs = 18,
    TidyEmacs = 19,
    TidyEmacsFile = 20,
    TidyEmptyTags = 21,
    TidyEncloseBlockText = 22,
    TidyEncloseBodyText = 23,
    TidyErrFile = 24,
    TidyEscapeCdata = 25,
    TidyEscapeScripts = 26,
    TidyFixBackslash = 27,
    TidyFixComments = 28,
    TidyFixUri = 29,
    TidyForceOutput = 30,
    TidyGDocClean = 31,
    TidyHideComments = 32,
    TidyHtmlOut = 33,
    TidyInCharEncoding = 34,
    TidyIndentAttributes = 35,
    TidyIndentCdata = 36,
    TidyIndentContent = 37,
    TidyIndentSpaces = 38,
    TidyInlineTags = 39,
    TidyJoinClasses = 40,
    TidyJoinStyles = 41,
    TidyKeepFileTimes = 42,
    TidyKeepTabs = 43,
    TidyLiteralAttribs = 44,
    TidyLogicalEmphasis = 45,
    TidyLowerLiterals = 46,
    TidyMakeBare = 47,
    TidyMakeClean = 48,
    TidyMark = 49,
    TidyMergeDivs = 50,
    TidyMergeEmphasis = 51,
    TidyMergeSpans = 52,
    TidyMetaCharset = 53,
    TidyMuteReports = 54,
    TidyMuteShow = 55,
    TidyNCR = 56,
    TidyNewline = 57,
    TidyNumEntities = 58,
    TidyOmitOptionalTags = 59,
    TidyOutCharEncoding = 60,
    TidyOutFile = 61,
    TidyOutputBOM = 62,
    TidyPPrintTabs = 63,
    TidyPreserveEntities = 64,
    TidyPreTags = 65,
    TidyPriorityAttributes = 66,
    TidyPunctWrap = 67,
    TidyQuiet = 68,
    TidyQuoteAmpersand = 69,
    TidyQuoteMarks = 70,
    TidyQuoteNbsp = 71,
    TidyReplaceColor = 72,
    TidyShowErrors = 73,
    TidyShowInfo = 74,
    TidyShowMarkup = 75,
    TidyShowMetaChange = 76,
    TidyShowWarnings = 77,
    TidySkipNested = 78,
    TidySortAttributes = 79,
    TidyStrictTagsAttr = 80,
    TidyStyleTags = 81,
    TidyTabSize = 82,
    TidyUpperCaseAttrs = 83,
    TidyUpperCaseTags = 84,
    TidyUseCustomTags = 85,
    TidyVertSpace = 86,
    TidyWarnPropAttrs = 87,
    TidyWord2000 = 88,
    TidyWrapAsp = 89,
    TidyWrapAttVals = 90,
    TidyWrapJste = 91,
    TidyWrapLen = 92,
    TidyWrapPhp = 93,
    TidyWrapScriptlets = 94,
    TidyWrapSection = 95,
    TidyWriteBack = 96,
    TidyXhtmlOut = 97,
    TidyXmlDecl = 98,
    TidyXmlOut = 99,
    TidyXmlPIs = 100,
    TidyXmlSpace = 101,
    TidyXmlTags = 102,
    N_TIDY_OPTIONS = 103,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyConfigCategory {
    TidyUnknownCategory = 300,
    TidyDiagnostics = 301,
    TidyDisplay = 302,
    TidyDocumentIO = 303,
    TidyEncoding = 304,
    TidyFileIO = 305,
    TidyMarkupCleanup = 306,
    TidyMarkupEntities = 307,
    TidyMarkupRepair = 308,
    TidyMarkupTeach = 309,
    TidyMarkupXForm = 310,
    TidyPrettyPrint = 311,
    TidyInternalCategory = 312,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyOptionType {
    TidyString = 0,
    TidyInteger = 1,
    TidyBoolean = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyNodeType {
    TidyNode_Root = 0,
    TidyNode_DocType = 1,
    TidyNode_Comment = 2,
    TidyNode_ProcIns = 3,
    TidyNode_Text = 4,
    TidyNode_Start = 5,
    TidyNode_End = 6,
    TidyNode_StartEnd = 7,
    TidyNode_CDATA = 8,
    TidyNode_Section = 9,
    TidyNode_Asp = 10,
    TidyNode_Jste = 11,
    TidyNode_Php = 12,
    TidyNode_XmlDecl = 13,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyTagId {
    TidyTag_UNKNOWN = 0,
    TidyTag_A = 1,
    TidyTag_ABBR = 2,
    TidyTag_ACRONYM = 3,
    TidyTag_ADDRESS = 4,
    TidyTag_ALIGN = 5,
    TidyTag_APPLET = 6,
    TidyTag_AREA = 7,
    TidyTag_B = 8,
    TidyTag_BASE = 9,
    TidyTag_BASEFONT = 10,
    TidyTag_BDO = 11,
    TidyTag_BGSOUND = 12,
    TidyTag_BIG = 13,
    TidyTag_BLINK = 14,
    TidyTag_BLOCKQUOTE = 15,
    TidyTag_BODY = 16,
    TidyTag_BR = 17,
    TidyTag_BUTTON = 18,
    TidyTag_CAPTION = 19,
    TidyTag_CENTER = 20,
    TidyTag_CITE = 21,
    TidyTag_CODE = 22,
    TidyTag_COL = 23,
    TidyTag_COLGROUP = 24,
    TidyTag_COMMENT = 25,
    TidyTag_DD = 26,
    TidyTag_DEL = 27,
    TidyTag_DFN = 28,
    TidyTag_DIR = 29,
    TidyTag_DIV = 30,
    TidyTag_DL = 31,
    TidyTag_DT = 32,
    TidyTag_EM = 33,
    TidyTag_EMBED = 34,
    TidyTag_FIELDSET = 35,
    TidyTag_FONT = 36,
    TidyTag_FORM = 37,
    TidyTag_FRAME = 38,
    TidyTag_FRAMESET = 39,
    TidyTag_H1 = 40,
    TidyTag_H2 = 41,
    TidyTag_H3 = 42,
    TidyTag_H4 = 43,
    TidyTag_H5 = 44,
    TidyTag_H6 = 45,
    TidyTag_HEAD = 46,
    TidyTag_HR = 47,
    TidyTag_HTML = 48,
    TidyTag_I = 49,
    TidyTag_IFRAME = 50,
    TidyTag_ILAYER = 51,
    TidyTag_IMG = 52,
    TidyTag_INPUT = 53,
    TidyTag_INS = 54,
    TidyTag_ISINDEX = 55,
    TidyTag_KBD = 56,
    TidyTag_KEYGEN = 57,
    TidyTag_LABEL = 58,
    TidyTag_LAYER = 59,
    TidyTag_LEGEND = 60,
    TidyTag_LI = 61,
    TidyTag_LINK = 62,
    TidyTag_LISTING = 63,
    TidyTag_MAP = 64,
    TidyTag_MATHML = 65,
    TidyTag_MARQUEE = 66,
    TidyTag_MENU = 67,
    TidyTag_META = 68,
    TidyTag_MULTICOL = 69,
    TidyTag_NOBR = 70,
    TidyTag_NOEMBED = 71,
    TidyTag_NOFRAMES = 72,
    TidyTag_NOLAYER = 73,
    TidyTag_NOSAVE = 74,
    TidyTag_NOSCRIPT = 75,
    TidyTag_OBJECT = 76,
    TidyTag_OL = 77,
    TidyTag_OPTGROUP = 78,
    TidyTag_OPTION = 79,
    TidyTag_P = 80,
    TidyTag_PARAM = 81,
    TidyTag_PICTURE = 82,
    TidyTag_PLAINTEXT = 83,
    TidyTag_PRE = 84,
    TidyTag_Q = 85,
    TidyTag_RB = 86,
    TidyTag_RBC = 87,
    TidyTag_RP = 88,
    TidyTag_RT = 89,
    TidyTag_RTC = 90,
    TidyTag_RUBY = 91,
    TidyTag_S = 92,
    TidyTag_SAMP = 93,
    TidyTag_SCRIPT = 94,
    TidyTag_SELECT = 95,
    TidyTag_SERVER = 96,
    TidyTag_SERVLET = 97,
    TidyTag_SMALL = 98,
    TidyTag_SPACER = 99,
    TidyTag_SPAN = 100,
    TidyTag_STRIKE = 101,
    TidyTag_STRONG = 102,
    TidyTag_STYLE = 103,
    TidyTag_SUB = 104,
    TidyTag_SUP = 105,
    TidyTag_SVG = 106,
    TidyTag_TABLE = 107,
    TidyTag_TBODY = 108,
    TidyTag_TD = 109,
    TidyTag_TEXTAREA = 110,
    TidyTag_TFOOT = 111,
    TidyTag_TH = 112,
    TidyTag_THEAD = 113,
    TidyTag_TITLE = 114,
    TidyTag_TR = 115,
    TidyTag_TT = 116,
    TidyTag_U = 117,
    TidyTag_UL = 118,
    TidyTag_VAR = 119,
    TidyTag_WBR = 120,
    TidyTag_XMP = 121,
    TidyTag_NEXTID = 122,
    TidyTag_ARTICLE = 123,
    TidyTag_ASIDE = 124,
    TidyTag_AUDIO = 125,
    TidyTag_BDI = 126,
    TidyTag_CANVAS = 127,
    TidyTag_COMMAND = 128,
    TidyTag_DATALIST = 129,
    TidyTag_DETAILS = 130,
    TidyTag_DIALOG = 131,
    TidyTag_FIGCAPTION = 132,
    TidyTag_FIGURE = 133,
    TidyTag_FOOTER = 134,
    TidyTag_HEADER = 135,
    TidyTag_HGROUP = 136,
    TidyTag_MAIN = 137,
    TidyTag_MARK = 138,
    TidyTag_MENUITEM = 139,
    TidyTag_METER = 140,
    TidyTag_NAV = 141,
    TidyTag_OUTPUT = 142,
    TidyTag_PROGRESS = 143,
    TidyTag_SECTION = 144,
    TidyTag_SOURCE = 145,
    TidyTag_SUMMARY = 146,
    TidyTag_TEMPLATE = 147,
    TidyTag_TIME = 148,
    TidyTag_TRACK = 149,
    TidyTag_VIDEO = 150,
    N_TIDY_TAGS = 151,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyAttrId {
    TidyAttr_UNKNOWN = 0,
    TidyAttr_ABBR = 1,
    TidyAttr_ACCEPT = 2,
    TidyAttr_ACCEPT_CHARSET = 3,
    TidyAttr_ACCESSKEY = 4,
    TidyAttr_ACTION = 5,
    TidyAttr_ADD_DATE = 6,
    TidyAttr_ALIGN = 7,
    TidyAttr_ALINK = 8,
    TidyAttr_ALLOWFULLSCREEN = 9,
    TidyAttr_ALT = 10,
    TidyAttr_ARCHIVE = 11,
    TidyAttr_AXIS = 12,
    TidyAttr_BACKGROUND = 13,
    TidyAttr_BGCOLOR = 14,
    TidyAttr_BGPROPERTIES = 15,
    TidyAttr_BORDER = 16,
    TidyAttr_BORDERCOLOR = 17,
    TidyAttr_BOTTOMMARGIN = 18,
    TidyAttr_CELLPADDING = 19,
    TidyAttr_CELLSPACING = 20,
    TidyAttr_CHAR = 21,
    TidyAttr_CHAROFF = 22,
    TidyAttr_CHARSET = 23,
    TidyAttr_CHECKED = 24,
    TidyAttr_CITE = 25,
    TidyAttr_CLASS = 26,
    TidyAttr_CLASSID = 27,
    TidyAttr_CLEAR = 28,
    TidyAttr_CODE = 29,
    TidyAttr_CODEBASE = 30,
    TidyAttr_CODETYPE = 31,
    TidyAttr_COLOR = 32,
    TidyAttr_COLS = 33,
    TidyAttr_COLSPAN = 34,
    TidyAttr_COMPACT = 35,
    TidyAttr_CONTENT = 36,
    TidyAttr_COORDS = 37,
    TidyAttr_DATA = 38,
    TidyAttr_DATAFLD = 39,
    TidyAttr_DATAFORMATAS = 40,
    TidyAttr_DATAPAGESIZE = 41,
    TidyAttr_DATASRC = 42,
    TidyAttr_DATETIME = 43,
    TidyAttr_DECLARE = 44,
    TidyAttr_DEFER = 45,
    TidyAttr_DIR = 46,
    TidyAttr_DISABLED = 47,
    TidyAttr_DOWNLOAD = 48,
    TidyAttr_ENCODING = 49,
    TidyAttr_ENCTYPE = 50,
    TidyAttr_FACE = 51,
    TidyAttr_FOR = 52,
    TidyAttr_FRAME = 53,
    TidyAttr_FRAMEBORDER = 54,
    TidyAttr_FRAMESPACING = 55,
    TidyAttr_GRIDX = 56,
    TidyAttr_GRIDY = 57,
    TidyAttr_HEADERS = 58,
    TidyAttr_HEIGHT = 59,
    TidyAttr_HREF = 60,
    TidyAttr_HREFLANG = 61,
    TidyAttr_HSPACE = 62,
    TidyAttr_HTTP_EQUIV = 63,
    TidyAttr_ID = 64,
    TidyAttr_IS = 65,
    TidyAttr_ISMAP = 66,
    TidyAttr_ITEMID = 67,
    TidyAttr_ITEMPROP = 68,
    TidyAttr_ITEMREF = 69,
    TidyAttr_ITEMSCOPE = 70,
    TidyAttr_ITEMTYPE = 71,
    TidyAttr_LABEL = 72,
    TidyAttr_LANG = 73,
    TidyAttr_LANGUAGE = 74,
    TidyAttr_LAST_MODIFIED = 75,
    TidyAttr_LAST_VISIT = 76,
    TidyAttr_LEFTMARGIN = 77,
    TidyAttr_LINK = 78,
    TidyAttr_LONGDESC = 79,
    TidyAttr_LOWSRC = 80,
    TidyAttr_MARGINHEIGHT = 81,
    TidyAttr_MARGINWIDTH = 82,
    TidyAttr_MAXLENGTH = 83,
    TidyAttr_MEDIA = 84,
    TidyAttr_METHOD = 85,
    TidyAttr_MULTIPLE = 86,
    TidyAttr_NAME = 87,
    TidyAttr_NOHREF = 88,
    TidyAttr_NORESIZE = 89,
    TidyAttr_NOSHADE = 90,
    TidyAttr_NOWRAP = 91,
    TidyAttr_OBJECT = 92,
    TidyAttr_OnAFTERUPDATE = 93,
    TidyAttr_OnBEFOREUNLOAD = 94,
    TidyAttr_OnBEFOREUPDATE = 95,
    TidyAttr_OnBLUR = 96,
    TidyAttr_OnCHANGE = 97,
    TidyAttr_OnCLICK = 98,
    TidyAttr_OnDATAAVAILABLE = 99,
    TidyAttr_OnDATASETCHANGED = 100,
    TidyAttr_OnDATASETCOMPLETE = 101,
    TidyAttr_OnDBLCLICK = 102,
    TidyAttr_OnERRORUPDATE = 103,
    TidyAttr_OnFOCUS = 104,
    TidyAttr_OnKEYDOWN = 105,
    TidyAttr_OnKEYPRESS = 106,
    TidyAttr_OnKEYUP = 107,
    TidyAttr_OnLOAD = 108,
    TidyAttr_OnMOUSEDOWN = 109,
    TidyAttr_OnMOUSEMOVE = 110,
    TidyAttr_OnMOUSEOUT = 111,
    TidyAttr_OnMOUSEOVER = 112,
    TidyAttr_OnMOUSEUP = 113,
    TidyAttr_OnRESET = 114,
    TidyAttr_OnROWENTER = 115,
    TidyAttr_OnROWEXIT = 116,
    TidyAttr_OnSELECT = 117,
    TidyAttr_OnSUBMIT = 118,
    TidyAttr_OnUNLOAD = 119,
    TidyAttr_PROFILE = 120,
    TidyAttr_PROMPT = 121,
    TidyAttr_RBSPAN = 122,
    TidyAttr_READONLY = 123,
    TidyAttr_REL = 124,
    TidyAttr_REV = 125,
    TidyAttr_RIGHTMARGIN = 126,
    TidyAttr_ROLE = 127,
    TidyAttr_ROWS = 128,
    TidyAttr_ROWSPAN = 129,
    TidyAttr_RULES = 130,
    TidyAttr_SCHEME = 131,
    TidyAttr_SCOPE = 132,
    TidyAttr_SCROLLING = 133,
    TidyAttr_SELECTED = 134,
    TidyAttr_SHAPE = 135,
    TidyAttr_SHOWGRID = 136,
    TidyAttr_SHOWGRIDX = 137,
    TidyAttr_SHOWGRIDY = 138,
    TidyAttr_SIZE = 139,
    TidyAttr_SPAN = 140,
    TidyAttr_SRC = 141,
    TidyAttr_SRCSET = 142,
    TidyAttr_STANDBY = 143,
    TidyAttr_START = 144,
    TidyAttr_STYLE = 145,
    TidyAttr_SUMMARY = 146,
    TidyAttr_TABINDEX = 147,
    TidyAttr_TARGET = 148,
    TidyAttr_TEXT = 149,
    TidyAttr_TITLE = 150,
    TidyAttr_TOPMARGIN = 151,
    TidyAttr_TRANSLATE = 152,
    TidyAttr_TYPE = 153,
    TidyAttr_USEMAP = 154,
    TidyAttr_VALIGN = 155,
    TidyAttr_VALUE = 156,
    TidyAttr_VALUETYPE = 157,
    TidyAttr_VERSION = 158,
    TidyAttr_VLINK = 159,
    TidyAttr_VSPACE = 160,
    TidyAttr_WIDTH = 161,
    TidyAttr_WRAP = 162,
    TidyAttr_XML_LANG = 163,
    TidyAttr_XML_SPACE = 164,
    TidyAttr_XMLNS = 165,
    TidyAttr_EVENT = 166,
    TidyAttr_METHODS = 167,
    TidyAttr_N = 168,
    TidyAttr_SDAFORM = 169,
    TidyAttr_SDAPREF = 170,
    TidyAttr_SDASUFF = 171,
    TidyAttr_URN = 172,
    TidyAttr_ASYNC = 173,
    TidyAttr_AUTOCOMPLETE = 174,
    TidyAttr_AUTOFOCUS = 175,
    TidyAttr_AUTOPLAY = 176,
    TidyAttr_CHALLENGE = 177,
    TidyAttr_CONTENTEDITABLE = 178,
    TidyAttr_CONTEXTMENU = 179,
    TidyAttr_CONTROLS = 180,
    TidyAttr_CROSSORIGIN = 181,
    TidyAttr_DEFAULT = 182,
    TidyAttr_DIRNAME = 183,
    TidyAttr_DRAGGABLE = 184,
    TidyAttr_DROPZONE = 185,
    TidyAttr_FORM = 186,
    TidyAttr_FORMACTION = 187,
    TidyAttr_FORMENCTYPE = 188,
    TidyAttr_FORMMETHOD = 189,
    TidyAttr_FORMNOVALIDATE = 190,
    TidyAttr_FORMTARGET = 191,
    TidyAttr_HIDDEN = 192,
    TidyAttr_HIGH = 193,
    TidyAttr_ICON = 194,
    TidyAttr_KEYTYPE = 195,
    TidyAttr_KIND = 196,
    TidyAttr_LIST = 197,
    TidyAttr_LOOP = 198,
    TidyAttr_LOW = 199,
    TidyAttr_MANIFEST = 200,
    TidyAttr_MAX = 201,
    TidyAttr_MEDIAGROUP = 202,
    TidyAttr_MIN = 203,
    TidyAttr_NOVALIDATE = 204,
    TidyAttr_OPEN = 205,
    TidyAttr_OPTIMUM = 206,
    TidyAttr_OnABORT = 207,
    TidyAttr_OnAFTERPRINT = 208,
    TidyAttr_OnBEFOREPRINT = 209,
    TidyAttr_OnCANPLAY = 210,
    TidyAttr_OnCANPLAYTHROUGH = 211,
    TidyAttr_OnCONTEXTMENU = 212,
    TidyAttr_OnCUECHANGE = 213,
    TidyAttr_OnDRAG = 214,
    TidyAttr_OnDRAGEND = 215,
    TidyAttr_OnDRAGENTER = 216,
    TidyAttr_OnDRAGLEAVE = 217,
    TidyAttr_OnDRAGOVER = 218,
    TidyAttr_OnDRAGSTART = 219,
    TidyAttr_OnDROP = 220,
    TidyAttr_OnDURATIONCHANGE = 221,
    TidyAttr_OnEMPTIED = 222,
    TidyAttr_OnENDED = 223,
    TidyAttr_OnERROR = 224,
    TidyAttr_OnHASHCHANGE = 225,
    TidyAttr_OnINPUT = 226,
    TidyAttr_OnINVALID = 227,
    TidyAttr_OnLOADEDDATA = 228,
    TidyAttr_OnLOADEDMETADATA = 229,
    TidyAttr_OnLOADSTART = 230,
    TidyAttr_OnMESSAGE = 231,
    TidyAttr_OnMOUSEWHEEL = 232,
    TidyAttr_OnOFFLINE = 233,
    TidyAttr_OnONLINE = 234,
    TidyAttr_OnPAGEHIDE = 235,
    TidyAttr_OnPAGESHOW = 236,
    TidyAttr_OnPAUSE = 237,
    TidyAttr_OnPLAY = 238,
    TidyAttr_OnPLAYING = 239,
    TidyAttr_OnPOPSTATE = 240,
    TidyAttr_OnPROGRESS = 241,
    TidyAttr_OnRATECHANGE = 242,
    TidyAttr_OnREADYSTATECHANGE = 243,
    TidyAttr_OnREDO = 244,
    TidyAttr_OnRESIZE = 245,
    TidyAttr_OnSCROLL = 246,
    TidyAttr_OnSEEKED = 247,
    TidyAttr_OnSEEKING = 248,
    TidyAttr_OnSHOW = 249,
    TidyAttr_OnSTALLED = 250,
    TidyAttr_OnSTORAGE = 251,
    TidyAttr_OnSUSPEND = 252,
    TidyAttr_OnTIMEUPDATE = 253,
    TidyAttr_OnUNDO = 254,
    TidyAttr_OnVOLUMECHANGE = 255,
    TidyAttr_OnWAITING = 256,
    TidyAttr_PATTERN = 257,
    TidyAttr_PLACEHOLDER = 258,
    TidyAttr_POSTER = 259,
    TidyAttr_PRELOAD = 260,
    TidyAttr_PUBDATE = 261,
    TidyAttr_RADIOGROUP = 262,
    TidyAttr_REQUIRED = 263,
    TidyAttr_REVERSED = 264,
    TidyAttr_SANDBOX = 265,
    TidyAttr_SCOPED = 266,
    TidyAttr_SEAMLESS = 267,
    TidyAttr_SIZES = 268,
    TidyAttr_SPELLCHECK = 269,
    TidyAttr_SRCDOC = 270,
    TidyAttr_SRCLANG = 271,
    TidyAttr_STEP = 272,
    TidyAttr_ARIA_ACTIVEDESCENDANT = 273,
    TidyAttr_ARIA_ATOMIC = 274,
    TidyAttr_ARIA_AUTOCOMPLETE = 275,
    TidyAttr_ARIA_BUSY = 276,
    TidyAttr_ARIA_CHECKED = 277,
    TidyAttr_ARIA_CONTROLS = 278,
    TidyAttr_ARIA_DESCRIBEDBY = 279,
    TidyAttr_ARIA_DISABLED = 280,
    TidyAttr_ARIA_DROPEFFECT = 281,
    TidyAttr_ARIA_EXPANDED = 282,
    TidyAttr_ARIA_FLOWTO = 283,
    TidyAttr_ARIA_GRABBED = 284,
    TidyAttr_ARIA_HASPOPUP = 285,
    TidyAttr_ARIA_HIDDEN = 286,
    TidyAttr_ARIA_INVALID = 287,
    TidyAttr_ARIA_LABEL = 288,
    TidyAttr_ARIA_LABELLEDBY = 289,
    TidyAttr_ARIA_LEVEL = 290,
    TidyAttr_ARIA_LIVE = 291,
    TidyAttr_ARIA_MULTILINE = 292,
    TidyAttr_ARIA_MULTISELECTABLE = 293,
    TidyAttr_ARIA_ORIENTATION = 294,
    TidyAttr_ARIA_OWNS = 295,
    TidyAttr_ARIA_POSINSET = 296,
    TidyAttr_ARIA_PRESSED = 297,
    TidyAttr_ARIA_READONLY = 298,
    TidyAttr_ARIA_RELEVANT = 299,
    TidyAttr_ARIA_REQUIRED = 300,
    TidyAttr_ARIA_SELECTED = 301,
    TidyAttr_ARIA_SETSIZE = 302,
    TidyAttr_ARIA_SORT = 303,
    TidyAttr_ARIA_VALUEMAX = 304,
    TidyAttr_ARIA_VALUEMIN = 305,
    TidyAttr_ARIA_VALUENOW = 306,
    TidyAttr_ARIA_VALUETEXT = 307,
    TidyAttr_X = 308,
    TidyAttr_Y = 309,
    TidyAttr_VIEWBOX = 310,
    TidyAttr_PRESERVEASPECTRATIO = 311,
    TidyAttr_ZOOMANDPAN = 312,
    TidyAttr_BASEPROFILE = 313,
    TidyAttr_CONTENTSCRIPTTYPE = 314,
    TidyAttr_CONTENTSTYLETYPE = 315,
    TidyAttr_DISPLAY = 316,
    TidyAttr_ABOUT = 317,
    TidyAttr_DATATYPE = 318,
    TidyAttr_INLIST = 319,
    TidyAttr_PREFIX = 320,
    TidyAttr_PROPERTY = 321,
    TidyAttr_RESOURCE = 322,
    TidyAttr_TYPEOF = 323,
    TidyAttr_VOCAB = 324,
    TidyAttr_INTEGRITY = 325,
    TidyAttr_AS = 326,
    TidyAttr_XMLNSXLINK = 327,
    N_TIDY_ATTRIBS = 328,
}
impl TidyReportLevel {
    pub const TidyDialogueDoc: TidyReportLevel = TidyReportLevel::TidyDialogueFootnote;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyReportLevel {
    TidyInfo = 350,
    TidyWarning = 351,
    TidyConfig = 352,
    TidyAccess = 353,
    TidyError = 354,
    TidyBadDocument = 355,
    TidyFatal = 356,
    TidyDialogueSummary = 357,
    TidyDialogueInfo = 358,
    TidyDialogueFootnote = 359,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum TidyFormatParameterType {
    tidyFormatType_INT = 0,
    tidyFormatType_UINT = 1,
    tidyFormatType_STRING = 2,
    tidyFormatType_DOUBLE = 3,
    tidyFormatType_UNKNOWN = 20,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyDoc {
    pub _opaque: ::std::os::raw::c_int,
}
pub type TidyDoc = *const _TidyDoc;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
 pub struct _TidyOption {
        pub TidyOptionId: ::std::os::raw::c_int,
        pub TidyConfigCategory: TidyConfigCategory,
        pub name: ctmbstr,
    }
pub type TidyOption = *const _TidyOption;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyNode {
    pub _opaque: ::std::os::raw::c_int,
}
pub type TidyNode = *const _TidyNode;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyAttr {
    pub _opaque: ::std::os::raw::c_int,
}
pub type TidyAttr = *const _TidyAttr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyMessage {
    pub _opaque: ::std::os::raw::c_int,
}
pub type TidyMessage = *const _TidyMessage;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyMessageArgument {
    pub _opaque: ::std::os::raw::c_int,
}
pub type TidyMessageArgument = *const _TidyMessageArgument;
pub type TidyAllocatorVtbl = _TidyAllocatorVtbl;
pub type TidyAllocator = _TidyAllocator;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyAllocator {
    pub vtbl: *const TidyAllocatorVtbl,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyAllocatorVtbl {
    pub alloc: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut TidyAllocator,
            nBytes: size_t,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub realloc: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut TidyAllocator,
            block: *mut ::std::os::raw::c_void,
            nBytes: size_t,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub free: ::std::option::Option<
        unsafe extern "C" fn(self_: *mut TidyAllocator, block: *mut ::std::os::raw::c_void),
    >,
    pub panic: ::std::option::Option<unsafe extern "C" fn(self_: *mut TidyAllocator, msg: ctmbstr)>,
}
pub type TidyMalloc =
    ::std::option::Option<unsafe extern "C" fn(len: size_t) -> *mut ::std::os::raw::c_void>;
pub type TidyRealloc = ::std::option::Option<
    unsafe extern "C" fn(
        buf: *mut ::std::os::raw::c_void,
        len: size_t,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type TidyFree = ::std::option::Option<unsafe extern "C" fn(buf: *mut ::std::os::raw::c_void)>;
pub type TidyPanic = ::std::option::Option<unsafe extern "C" fn(mssg: ctmbstr)>;
extern "C" {
    pub fn tidySetMallocCall(fmalloc: TidyMalloc) -> Bool;
}
extern "C" {
    pub fn tidySetReallocCall(frealloc: TidyRealloc) -> Bool;
}
extern "C" {
    pub fn tidySetFreeCall(ffree: TidyFree) -> Bool;
}
extern "C" {
    pub fn tidySetPanicCall(fpanic: TidyPanic) -> Bool;
}
extern "C" {
    pub fn tidyCreate() -> TidyDoc;
}
extern "C" {
    pub fn tidyCreateWithAllocator(allocator: *mut TidyAllocator) -> TidyDoc;
}
extern "C" {
    pub fn tidyRelease(tdoc: TidyDoc);
}
extern "C" {
    pub fn tidySetAppData(tdoc: TidyDoc, appData: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn tidyGetAppData(tdoc: TidyDoc) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn tidyReleaseDate() -> ctmbstr;
}
extern "C" {
    pub fn tidyLibraryVersion() -> ctmbstr;
}
extern "C" {
    pub fn tidyPlatform() -> ctmbstr;
}
extern "C" {
    pub fn tidyStatus(tdoc: TidyDoc) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyDetectedHtmlVersion(tdoc: TidyDoc) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyDetectedXhtml(tdoc: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyDetectedGenericXml(tdoc: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyErrorCount(tdoc: TidyDoc) -> uint;
}
extern "C" {
    pub fn tidyWarningCount(tdoc: TidyDoc) -> uint;
}
extern "C" {
    pub fn tidyAccessWarningCount(tdoc: TidyDoc) -> uint;
}
extern "C" {
    pub fn tidyConfigErrorCount(tdoc: TidyDoc) -> uint;
}
extern "C" {
    pub fn tidyErrorSummary(tdoc: TidyDoc);
}
extern "C" {
    pub fn tidyGeneralInfo(tdoc: TidyDoc);
}
extern "C" {
    pub fn tidyLoadConfig(tdoc: TidyDoc, configFile: ctmbstr) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyLoadConfigEnc(
        tdoc: TidyDoc,
        configFile: ctmbstr,
        charenc: ctmbstr,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyFileExists(tdoc: TidyDoc, filename: ctmbstr) -> Bool;
}
extern "C" {
    pub fn tidySetCharEncoding(tdoc: TidyDoc, encnam: ctmbstr) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySetInCharEncoding(tdoc: TidyDoc, encnam: ctmbstr) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySetOutCharEncoding(tdoc: TidyDoc, encnam: ctmbstr) -> ::std::os::raw::c_int;
}
pub type TidyOptCallback =
    ::std::option::Option<unsafe extern "C" fn(option: ctmbstr, value: ctmbstr) -> Bool>;
extern "C" {
    pub fn tidySetOptionCallback(tdoc: TidyDoc, pOptCallback: TidyOptCallback) -> Bool;
}
pub type TidyConfigCallback = ::std::option::Option<
    unsafe extern "C" fn(tdoc: TidyDoc, option: ctmbstr, value: ctmbstr) -> Bool,
>;
extern "C" {
    pub fn tidySetConfigCallback(tdoc: TidyDoc, pConfigCallback: TidyConfigCallback) -> Bool;
}
pub type TidyConfigChangeCallback =
    ::std::option::Option<unsafe extern "C" fn(tdoc: TidyDoc, option: TidyOption)>;
extern "C" {
    pub fn tidySetConfigChangeCallback(tdoc: TidyDoc, pCallback: TidyConfigChangeCallback) -> Bool;
}
extern "C" {
    pub fn tidyOptGetId(opt: TidyOption) -> TidyOptionId;
}
extern "C" {
    pub fn tidyOptGetIdForName(optnam: ctmbstr) -> TidyOptionId;
}
extern "C" {
    pub fn tidyGetOptionList(tdoc: TidyDoc) -> TidyIterator;
}
extern "C" {
    pub fn tidyGetNextOption(tdoc: TidyDoc, pos: *mut TidyIterator) -> TidyOption;
}
extern "C" {
    pub fn tidyGetOption(tdoc: TidyDoc, optId: TidyOptionId) -> TidyOption;
}
extern "C" {
    pub fn tidyGetOptionByName(tdoc: TidyDoc, optnam: ctmbstr) -> TidyOption;
}
extern "C" {
    pub fn tidyOptGetName(opt: TidyOption) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetType(opt: TidyOption) -> TidyOptionType;
}
extern "C" {
    pub fn tidyOptionIsList(opt: TidyOption) -> Bool;
}
extern "C" {
    pub fn tidyOptIsReadOnly(opt: TidyOption) -> Bool;
}
extern "C" {
    pub fn tidyOptGetCategory(opt: TidyOption) -> TidyConfigCategory;
}
extern "C" {
    pub fn tidyOptGetDefault(opt: TidyOption) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetDefaultInt(opt: TidyOption) -> ulong;
}
extern "C" {
    pub fn tidyOptGetDefaultBool(opt: TidyOption) -> Bool;
}
extern "C" {
    pub fn tidyOptGetPickList(opt: TidyOption) -> TidyIterator;
}
extern "C" {
    pub fn tidyOptGetNextPick(opt: TidyOption, pos: *mut TidyIterator) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetValue(tdoc: TidyDoc, optId: TidyOptionId) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptSetValue(tdoc: TidyDoc, optId: TidyOptionId, val: ctmbstr) -> Bool;
}
extern "C" {
    pub fn tidyOptParseValue(tdoc: TidyDoc, optnam: ctmbstr, val: ctmbstr) -> Bool;
}
extern "C" {
    pub fn tidyOptGetInt(tdoc: TidyDoc, optId: TidyOptionId) -> ulong;
}
extern "C" {
    pub fn tidyOptSetInt(tdoc: TidyDoc, optId: TidyOptionId, val: ulong) -> Bool;
}
extern "C" {
    pub fn tidyOptGetBool(tdoc: TidyDoc, optId: TidyOptionId) -> Bool;
}
extern "C" {
    pub fn tidyOptSetBool(tdoc: TidyDoc, optId: TidyOptionId, val: Bool) -> Bool;
}
extern "C" {
    pub fn tidyOptResetToDefault(tdoc: TidyDoc, opt: TidyOptionId) -> Bool;
}
extern "C" {
    pub fn tidyOptResetAllToDefault(tdoc: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyOptSnapshot(tdoc: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyOptResetToSnapshot(tdoc: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyOptDiffThanDefault(tdoc: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyOptDiffThanSnapshot(tdoc: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyOptCopyConfig(tdocTo: TidyDoc, tdocFrom: TidyDoc) -> Bool;
}
extern "C" {
    pub fn tidyOptGetEncName(tdoc: TidyDoc, optId: TidyOptionId) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetCurrPick(tdoc: TidyDoc, optId: TidyOptionId) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetDeclTagList(tdoc: TidyDoc) -> TidyIterator;
}
extern "C" {
    pub fn tidyOptGetNextDeclTag(
        tdoc: TidyDoc,
        optId: TidyOptionId,
        iter: *mut TidyIterator,
    ) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetPriorityAttrList(tdoc: TidyDoc) -> TidyIterator;
}
extern "C" {
    pub fn tidyOptGetNextPriorityAttr(tdoc: TidyDoc, iter: *mut TidyIterator) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetMutedMessageList(tdoc: TidyDoc) -> TidyIterator;
}
extern "C" {
    pub fn tidyOptGetNextMutedMessage(tdoc: TidyDoc, iter: *mut TidyIterator) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetDoc(tdoc: TidyDoc, opt: TidyOption) -> ctmbstr;
}
extern "C" {
    pub fn tidyOptGetDocLinksList(tdoc: TidyDoc, opt: TidyOption) -> TidyIterator;
}
extern "C" {
    pub fn tidyOptGetNextDocLinks(tdoc: TidyDoc, pos: *mut TidyIterator) -> TidyOption;
}
pub type TidyBuffer = _TidyBuffer;
pub type TidyGetByteFunc = ::std::option::Option<
    unsafe extern "C" fn(sourceData: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
pub type TidyUngetByteFunc =
    ::std::option::Option<unsafe extern "C" fn(sourceData: *mut ::std::os::raw::c_void, bt: byte)>;
pub type TidyEOFFunc =
    ::std::option::Option<unsafe extern "C" fn(sourceData: *mut ::std::os::raw::c_void) -> Bool>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyInputSource {
    pub sourceData: *mut ::std::os::raw::c_void,
    pub getByte: TidyGetByteFunc,
    pub ungetByte: TidyUngetByteFunc,
    pub eof: TidyEOFFunc,
}
pub type TidyInputSource = _TidyInputSource;
extern "C" {
    pub fn tidyInitSource(
        source: *mut TidyInputSource,
        srcData: *mut ::std::os::raw::c_void,
        gbFunc: TidyGetByteFunc,
        ugbFunc: TidyUngetByteFunc,
        endFunc: TidyEOFFunc,
    ) -> Bool;
}
extern "C" {
    pub fn tidyGetByte(source: *mut TidyInputSource) -> uint;
}
extern "C" {
    pub fn tidyUngetByte(source: *mut TidyInputSource, byteValue: uint);
}
extern "C" {
    pub fn tidyIsEOF(source: *mut TidyInputSource) -> Bool;
}
pub type TidyPutByteFunc =
    ::std::option::Option<unsafe extern "C" fn(sinkData: *mut ::std::os::raw::c_void, bt: byte)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyOutputSink {
    pub sinkData: *mut ::std::os::raw::c_void,
    pub putByte: TidyPutByteFunc,
}
pub type TidyOutputSink = _TidyOutputSink;
extern "C" {
    pub fn tidyInitSink(
        sink: *mut TidyOutputSink,
        snkData: *mut ::std::os::raw::c_void,
        pbFunc: TidyPutByteFunc,
    ) -> Bool;
}
extern "C" {
    pub fn tidyPutByte(sink: *mut TidyOutputSink, byteValue: uint);
}
extern "C" {
    pub fn tidySetEmacsFile(tdoc: TidyDoc, filePath: ctmbstr);
}
extern "C" {
    pub fn tidyGetEmacsFile(tdoc: TidyDoc) -> ctmbstr;
}
extern "C" {
    pub fn tidySetErrorFile(tdoc: TidyDoc, errfilnam: ctmbstr) -> *mut FILE;
}
extern "C" {
    pub fn tidySetErrorBuffer(tdoc: TidyDoc, errbuf: *mut TidyBuffer) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySetErrorSink(tdoc: TidyDoc, sink: *mut TidyOutputSink) -> ::std::os::raw::c_int;
}
pub type TidyReportFilter = ::std::option::Option<
    unsafe extern "C" fn(
        tdoc: TidyDoc,
        lvl: TidyReportLevel,
        line: uint,
        col: uint,
        mssg: ctmbstr,
    ) -> Bool,
>;
extern "C" {
    pub fn tidySetReportFilter(tdoc: TidyDoc, filtCallback: TidyReportFilter) -> Bool;
}
pub type TidyReportCallback = ::std::option::Option<
    unsafe extern "C" fn(
        tdoc: TidyDoc,
        lvl: TidyReportLevel,
        line: uint,
        col: uint,
        code: ctmbstr,
        args: *mut __va_list_tag,
    ) -> Bool,
>;
extern "C" {
    pub fn tidySetReportCallback(tdoc: TidyDoc, filtCallback: TidyReportCallback) -> Bool;
}
pub type TidyMessageCallback =
    ::std::option::Option<unsafe extern "C" fn(tmessage: TidyMessage) -> Bool>;
extern "C" {
    pub fn tidySetMessageCallback(tdoc: TidyDoc, filtCallback: TidyMessageCallback) -> Bool;
}
extern "C" {
    pub fn tidyGetMessageDoc(tmessage: TidyMessage) -> TidyDoc;
}
extern "C" {
    pub fn tidyGetMessageCode(tmessage: TidyMessage) -> uint;
}
extern "C" {
    pub fn tidyGetMessageKey(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessageLine(tmessage: TidyMessage) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyGetMessageColumn(tmessage: TidyMessage) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyGetMessageLevel(tmessage: TidyMessage) -> TidyReportLevel;
}
extern "C" {
    pub fn tidyGetMessageIsMuted(tmessage: TidyMessage) -> Bool;
}
extern "C" {
    pub fn tidyGetMessageFormatDefault(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessageFormat(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessageDefault(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessage(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessagePosDefault(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessagePos(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessagePrefixDefault(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessagePrefix(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessageOutputDefault(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessageOutput(tmessage: TidyMessage) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetMessageArguments(tmessage: TidyMessage) -> TidyIterator;
}
extern "C" {
    pub fn tidyGetNextMessageArgument(
        tmessage: TidyMessage,
        iter: *mut TidyIterator,
    ) -> TidyMessageArgument;
}
extern "C" {
    pub fn tidyGetArgType(
        tmessage: TidyMessage,
        arg: *mut TidyMessageArgument,
    ) -> TidyFormatParameterType;
}
extern "C" {
    pub fn tidyGetArgFormat(tmessage: TidyMessage, arg: *mut TidyMessageArgument) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetArgValueString(tmessage: TidyMessage, arg: *mut TidyMessageArgument) -> ctmbstr;
}
extern "C" {
    pub fn tidyGetArgValueUInt(tmessage: TidyMessage, arg: *mut TidyMessageArgument) -> uint;
}
extern "C" {
    pub fn tidyGetArgValueInt(
        tmessage: TidyMessage,
        arg: *mut TidyMessageArgument,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyGetArgValueDouble(tmessage: TidyMessage, arg: *mut TidyMessageArgument) -> f64;
}
pub type TidyPPProgress = ::std::option::Option<
    unsafe extern "C" fn(tdoc: TidyDoc, line: uint, col: uint, destLine: uint),
>;
extern "C" {
    pub fn tidySetPrettyPrinterCallback(tdoc: TidyDoc, callback: TidyPPProgress) -> Bool;
}
extern "C" {
    pub fn tidyParseFile(tdoc: TidyDoc, filename: ctmbstr) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyParseStdin(tdoc: TidyDoc) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyParseString(tdoc: TidyDoc, content: ctmbstr) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyParseBuffer(tdoc: TidyDoc, buf: *mut TidyBuffer) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyParseSource(tdoc: TidyDoc, source: *mut TidyInputSource) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyCleanAndRepair(tdoc: TidyDoc) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyRunDiagnostics(tdoc: TidyDoc) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyReportDoctype(tdoc: TidyDoc) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySaveFile(tdoc: TidyDoc, filename: ctmbstr) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySaveStdout(tdoc: TidyDoc) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySaveBuffer(tdoc: TidyDoc, buf: *mut TidyBuffer) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySaveString(
        tdoc: TidyDoc,
        buffer: tmbstr,
        buflen: *mut uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidySaveSink(tdoc: TidyDoc, sink: *mut TidyOutputSink) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyOptSaveFile(tdoc: TidyDoc, cfgfil: ctmbstr) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyOptSaveSink(tdoc: TidyDoc, sink: *mut TidyOutputSink) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyGetRoot(tdoc: TidyDoc) -> TidyNode;
}
extern "C" {
    pub fn tidyGetHtml(tdoc: TidyDoc) -> TidyNode;
}
extern "C" {
    pub fn tidyGetHead(tdoc: TidyDoc) -> TidyNode;
}
extern "C" {
    pub fn tidyGetBody(tdoc: TidyDoc) -> TidyNode;
}
extern "C" {
    pub fn tidyGetParent(tnod: TidyNode) -> TidyNode;
}
extern "C" {
    pub fn tidyGetChild(tnod: TidyNode) -> TidyNode;
}
extern "C" {
    pub fn tidyGetNext(tnod: TidyNode) -> TidyNode;
}
extern "C" {
    pub fn tidyGetPrev(tnod: TidyNode) -> TidyNode;
}
extern "C" {
    pub fn tidyDiscardElement(tdoc: TidyDoc, tnod: TidyNode) -> TidyNode;
}
extern "C" {
    pub fn tidyAttrFirst(tnod: TidyNode) -> TidyAttr;
}
extern "C" {
    pub fn tidyAttrNext(tattr: TidyAttr) -> TidyAttr;
}
extern "C" {
    pub fn tidyAttrName(tattr: TidyAttr) -> ctmbstr;
}
extern "C" {
    pub fn tidyAttrValue(tattr: TidyAttr) -> ctmbstr;
}
extern "C" {
    pub fn tidyAttrDiscard(itdoc: TidyDoc, tnod: TidyNode, tattr: TidyAttr);
}
extern "C" {
    pub fn tidyAttrGetId(tattr: TidyAttr) -> TidyAttrId;
}
extern "C" {
    pub fn tidyAttrIsEvent(tattr: TidyAttr) -> Bool;
}
extern "C" {
    pub fn tidyAttrGetById(tnod: TidyNode, attId: TidyAttrId) -> TidyAttr;
}
extern "C" {
    pub fn tidyNodeGetType(tnod: TidyNode) -> TidyNodeType;
}
extern "C" {
    pub fn tidyNodeGetName(tnod: TidyNode) -> ctmbstr;
}
extern "C" {
    pub fn tidyNodeIsText(tnod: TidyNode) -> Bool;
}
extern "C" {
    pub fn tidyNodeIsProp(tdoc: TidyDoc, tnod: TidyNode) -> Bool;
}
extern "C" {
    pub fn tidyNodeIsHeader(tnod: TidyNode) -> Bool;
}
extern "C" {
    pub fn tidyNodeHasText(tdoc: TidyDoc, tnod: TidyNode) -> Bool;
}
extern "C" {
    pub fn tidyNodeGetText(tdoc: TidyDoc, tnod: TidyNode, buf: *mut TidyBuffer) -> Bool;
}
extern "C" {
    pub fn tidyNodeGetValue(tdoc: TidyDoc, tnod: TidyNode, buf: *mut TidyBuffer) -> Bool;
}
extern "C" {
    pub fn tidyNodeGetId(tnod: TidyNode) -> TidyTagId;
}
extern "C" {
    pub fn tidyNodeLine(tnod: TidyNode) -> uint;
}
extern "C" {
    pub fn tidyNodeColumn(tnod: TidyNode) -> uint;
}
extern "C" {
    pub fn tidyErrorCodeAsKey(code: uint) -> ctmbstr;
}
extern "C" {
    pub fn tidyErrorCodeFromKey(code: ctmbstr) -> uint;
}
extern "C" {
    pub fn tidySetLanguage(languageCode: ctmbstr) -> Bool;
}
extern "C" {
    pub fn tidyGetLanguage() -> ctmbstr;
}
extern "C" {
    pub fn tidyLocalizedStringN(messageType: uint, quantity: uint) -> ctmbstr;
}
extern "C" {
    pub fn tidyLocalizedString(messageType: uint) -> ctmbstr;
}
extern "C" {
    pub fn tidyDefaultString(messageType: uint) -> ctmbstr;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _TidyBuffer {
    pub allocator: *mut TidyAllocator,
    pub bp: *mut byte,
    pub size: uint,
    pub allocated: uint,
    pub next: uint,
}
extern "C" {
    pub fn tidyBufInit(buf: *mut TidyBuffer);
}
extern "C" {
    pub fn tidyBufInitWithAllocator(buf: *mut TidyBuffer, allocator: *mut TidyAllocator);
}
extern "C" {
    pub fn tidyBufAlloc(buf: *mut TidyBuffer, allocSize: uint);
}
extern "C" {
    pub fn tidyBufAllocWithAllocator(
        buf: *mut TidyBuffer,
        allocator: *mut TidyAllocator,
        allocSize: uint,
    );
}
extern "C" {
    pub fn tidyBufCheckAlloc(buf: *mut TidyBuffer, allocSize: uint, chunkSize: uint);
}
extern "C" {
    pub fn tidyBufFree(buf: *mut TidyBuffer);
}
extern "C" {
    pub fn tidyBufClear(buf: *mut TidyBuffer);
}
extern "C" {
    pub fn tidyBufAttach(buf: *mut TidyBuffer, bp: *mut byte, size: uint);
}
extern "C" {
    pub fn tidyBufDetach(buf: *mut TidyBuffer);
}
extern "C" {
    pub fn tidyBufAppend(buf: *mut TidyBuffer, vp: *mut ::std::os::raw::c_void, size: uint);
}
extern "C" {
    pub fn tidyBufPutByte(buf: *mut TidyBuffer, bv: byte);
}
extern "C" {
    pub fn tidyBufPopByte(buf: *mut TidyBuffer) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyBufGetByte(buf: *mut TidyBuffer) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tidyBufEndOfInput(buf: *mut TidyBuffer) -> Bool;
}
extern "C" {
    pub fn tidyBufUngetByte(buf: *mut TidyBuffer, bv: byte);
}
extern "C" {
    pub fn tidyInitInputBuffer(inp: *mut TidyInputSource, buf: *mut TidyBuffer);
}
extern "C" {
    pub fn tidyInitOutputBuffer(outp: *mut TidyOutputSink, buf: *mut TidyBuffer);
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
