[package]
name = "tidy-bin"
version = "0.1.7"
authors = ["Wolfgang Grimm <grimm@mondial.at>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
tidy = { path = "../tidy-rs" }

